spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: c##mytest
        password: 20301007
        driver-class-name: oracle.jdbc.driver.OracleDriver
    jpa:
        show-sql: true
        properties:
          hibernate:
              format_sql: true
server:
    port: 8181